apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-injector-mutating-webhook
  namespace: custom-service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-injector
  template:
    metadata:
      labels:
        app: envoy-injector
    spec:
      containers:
      - image: patnaikshekhar/custom-service-mesh-injector:0.1
        imagePullPolicy: Always
        name: injector
        volumeMounts:
        - name: certs
          mountPath: /app/certs
      volumes:
      - name: certs
        secret:
          secretName: envoy-injector-secret
---
apiVersion: v1
kind: Service
metadata:
  name: injector-service
  namespace: custom-service-mesh
spec:
  type: ClusterIP
  selector:
    app: envoy-injector
  ports:
  - protocol: TCP
    port: 443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: custom-service-mesh
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    dynamic_resources:
      lds_config:
        api_config_source:
          api_type: REST
          refresh_delay: 10s
          cluster_names:
          - xds_cluster
      cds_config:
        api_config_source:
          api_type: REST
          refresh_delay: 10s
          cluster_names:
          - xds_cluster
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout:  0.25s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: xds-service
            port_value: 80
---