apiVersion: v1
kind: ServiceAccount
metadata:
  name: xds-server
  namespace: custom-service-mesh
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xds-server-binding
subjects:
- kind: ServiceAccount
  name: xds-server
  namespace: custom-service-mesh
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xds-server
  namespace: custom-service-mesh
spec:
  selector:
    matchLabels:
      app: xds-server
  template:
    metadata:
      labels:
        app: xds-server
    spec:
      serviceAccount: xds-server
      containers:
      - name: xds-server
        image: patnaikshekhar/custom-service-mesh-xds-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: xds-service
  namespace: custom-service-mesh
spec:
  type: ClusterIP
  selector:
    app: xds-server
  ports:
  - port: 80
    targetPort: 80
---